# Generated by Django 4.2.15 on 2024-08-26 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=125)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=125)),
                ("imagem_perfil", models.ImageField(upload_to="img/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wishlist",
                    models.ManyToManyField(
                        blank=True, related_name="wishlist", to="roms.rom"
                    ),
                ),
            ],
        ),
    ]
