# Generated by Django 4.2.15 on 2024-08-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0002_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="rom",
            name="emulador",
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="imagem_perfil",
            field=models.ImageField(upload_to="img/perfil/"),
        ),
    ]
