# Generated by Django 4.2.15 on 2024-09-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0002_categoria_forum_categoria_jogo_conversa_rom_emulador_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rom",
            name="emulador",
            field=models.CharField(default="Default Emulator", max_length=125),
        ),
    ]
