# Generated by Django 4.2.15 on 2024-08-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0003_rom_emulador_alter_user_imagem_perfil"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
