# Generated by Django 4.2.15 on 2024-09-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0003_alter_rom_emulador"),
    ]

    operations = [
        migrations.CreateModel(
            name="Emulador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=125)),
            ],
        ),
    ]
