# Generated by Django 4.2.15 on 2024-09-03 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0005_alter_user_imagem_perfil_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="rom",
            name="qtd_download",
            field=models.IntegerField(default=0),
        ),
    ]
