# Generated by Django 4.2.15 on 2024-10-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0007_auto_20241001_1654"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rom",
            old_name="id_categoria",
            new_name="categoria",
        ),
        migrations.RenameField(
            model_name="rom",
            old_name="id_emulador",
            new_name="emulador",
        ),
    ]
