# Generated by Django 4.2.15 on 2024-10-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0008_rename_id_categoria_rom_categoria_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emulador",
            name="console",
            field=models.CharField(default=1, max_length=125),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="emulador",
            name="empresa",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
