# Generated by Django 4.2.15 on 2024-10-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roms", "0010_auto_20241001_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="rom",
            name="empresa",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
